<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.376" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MenuManagerApi">
      <HintPath>3rd_party\MenuManagerApi.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
